const fs = require('fs');
const path = require('path');

const missingKeys = [
    'admin.btn_chat', 'admin.col_email', 'admin.col_id', 'admin.col_order_id', 'admin.col_role', 'admin.col_status', 'admin.col_total', 'admin.col_username', 'admin.dividend_desc',
    'auth.email_not_found', 'auth.error_generic', 'auth.password_mismatch', 'auth.password_reset_failed', 'auth.password_reset_success', 'auth.register_failed', 'auth.register_success', 'auth.request_failed', 'auth.reset_link_sent', 'auth.role_denied', 'auth.server_error', 'auth.token_invalid', 'auth.username_taken', 'auth.welcome_back', 'auth.wrong_credentials',
    'cart.cleared', 'cart.cleared_flash', 'cart.insufficient_stock', 'cart.item_removed', 'cart.item_removed_flash', 'cart.max_stock', 'cart.min_quantity', 'cart.out_of_stock', 'cart.own_product', 'cart.own_product_flash', 'cart.product_added', 'cart.product_added_quantity', 'cart.product_not_found', 'cart.server_error',
    'dashboard.store_save_failed', 'dashboard.store_updated',
    'order.already_rejected', 'order.cancel_failed', 'order.cancelled', 'order.cart_empty', 'order.checkout_failed', 'order.checkout_success_multi', 'order.checkout_success_single', 'order.complete_success', 'order.confirm_failed', 'order.delete_failed', 'order.hide_restriction', 'order.hide_restriction_short', 'order.history_removed', 'order.item_cancel_error', 'order.item_cancel_flash', 'order.item_cancelled', 'order.item_cannot_cancel', 'order.item_not_found', 'order.not_found', 'order.order_not_found', 'order.permanent_deleted', 'order.processed', 'order.reject_failed', 'order.rejected', 'order.seller_detail_denied', 'order.seller_process_failed', 'order.seller_reject_error', 'order.seller_stock_insufficient', 'order.ship_failed', 'order.shipped', 'order.stock_insufficient',
    'product.add_failed', 'product.added', 'product.delete_failed', 'product.deleted', 'product.not_found', 'product.store_not_found', 'product.update_failed', 'product.updated',
    'profile.active_orders', 'profile.active_seller_orders', 'profile.delete_failed', 'profile.edit_load_failed', 'profile.load_failed', 'profile.password_mismatch', 'profile.update_failed', 'profile.updated', 'profile.username_taken',
    'user.cannot_delete_self', 'user.delete_failed', 'user.deleted'
];

// Extremely basic auto-translator fallback for EN/ID
function generateTranslationObj(key) {
    const term = key.split('.')[1].replace(/_/g, ' ');
    const isSuccess = term.includes('success') || term.includes('added') || term.includes('updated') || term.includes('removed') || term.includes('cleared') || term.includes('processed') || term.includes('welcome') || term.includes('shipped') || term.includes('completed');
    const isError = term.includes('failed') || term.includes('error') || term.includes('denied') || term.includes('invalid') || term.includes('mismatch') || term.includes('not found') || term.includes('empty') || term.includes('insufficient');

    // Title case
    let textEN = term.replace(/\w\S*/g, (txt) => txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase());

    // Very rudimentary ID translations
    let textID = textEN;
    if (isSuccess) textID = 'Berhasil: ' + textEN;
    else if (isError) textID = 'Gagal: ' + textEN;

    // Better manual mapping for key phrases
    if (term.includes('added')) { textEN = 'Successfully Added'; textID = 'Berhasil Ditambahkan'; }
    if (term.includes('updated')) { textEN = 'Successfully Updated'; textID = 'Berhasil Diperbarui'; }
    if (term.includes('deleted')) { textEN = 'Successfully Deleted'; textID = 'Berhasil Dihapus'; }
    if (term.includes('removed')) { textEN = 'Successfully Removed'; textID = 'Berhasil Dihapus'; }
    if (term.includes('not found')) { textEN = 'Not Found'; textID = 'Tidak Ditemukan'; }
    if (term.includes('failed')) { textEN = 'Action Failed'; textID = 'Aksi Gagal'; }

    return `    // Auto-generated backend keys\n    '${key}': { id: '[ID] ${textID}', en: '[EN] ${textEN}' }`;
}

const linesToAdd = [];
missingKeys.forEach(k => {
    linesToAdd.push(generateTranslationObj(k));
});

const i18nPath = path.join(__dirname, 'public/js/i18n.js');
let i18nContent = fs.readFileSync(i18nPath, 'utf8');

// Insert right before `}; // <--- End Translations` or similar
const insertionPoint = i18nContent.lastIndexOf('};');
if (insertionPoint !== -1) {
    const before = i18nContent.slice(0, insertionPoint);
    const after = i18nContent.slice(insertionPoint);
    const newContent = before + ',\n\n    // ========== BACKEND AUTOGENERATED ==========\n' + linesToAdd.join(',\n') + '\n' + after;
    fs.writeFileSync(i18nPath, newContent);
    console.log('Successfully patched i18n.js with ' + missingKeys.length + ' keys.');
} else {
    console.log('Could not find insertion point in i18n.js');
}
